# Generated by Django 3.2.7 on 2021-09-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='grade',
            field=models.CharField(default='b', max_length=255),
        ),
    ]
