# Generated by Django 3.2.7 on 2021-09-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_users_user_email_6f2530_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_email_6f2530_idx',
        ),
    ]
