# Generated by Django 3.2.7 on 2021-09-28 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='all', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_valid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.DurationField()),
                ('slug', models.SlugField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.TimeField(default=django.utils.timezone.now)),
                ('time_taken', models.TimeField()),
                ('score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_Exam_Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_api.choice')),
                ('student_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_api.student_exam')),
            ],
            options={
                'unique_together': {('student_exam', 'choice')},
            },
        ),
        migrations.AddField(
            model_name='student_exam',
            name='choices',
            field=models.ManyToManyField(through='quiz_api.Student_Exam_Choices', to='quiz_api.Choice'),
        ),
        migrations.AddField(
            model_name='student_exam',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_api.exam'),
        ),
        migrations.AddField(
            model_name='student_exam',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_api.category')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz_api.exam')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='students',
            field=models.ManyToManyField(through='quiz_api.Student_Exam', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_api.question'),
        ),
    ]
