# Generated by Django 3.2.7 on 2021-09-28 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_users_user_email_6f2530_idx'),
        ('quiz_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='students',
            field=models.ManyToManyField(through='quiz_api.Student_Exam', to='users.Student'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='users.teacher'),
        ),
        migrations.AlterField(
            model_name='student_exam',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
