# Generated by Django 3.2.7 on 2021-12-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0005_alter_choice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='desciption',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
