# Generated by Django 3.2.7 on 2021-12-09 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0006_exam_desciption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='desciption',
            new_name='description',
        ),
    ]
